version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./mysql/conf/:/etc/mysql/conf.d/
      - ./mysql/data:/var/lib/mysql
      - ./mysql/backup:/tmp/backup
    ports:
      - "3306:3306"
